# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Lunderberg
tagline:          'The Lunderblog'
description:      'Assorted wanderings through physics, math, and programming'
url:              http://www.lunderberg.com
baseurl:          /

author:
  name:           'Eric Lunderberg'
  url:            https://github.com/Lunderberg

paginate:         5

# Custom vars
version:          2.1.0

github:
  url:           https://github.com/Lunderberg


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true